config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :invites, only: [:index, :edit, :update]
  end
  post '/events/:event_id/invites/new' => 'invites#create'
  resources :events, only: [:show, :new, :create, :destroy] do
    resources :invites, only: :new
  end
  resources :invites, only: :destroy

end

app/models/invite.rb
class Invite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event

  validates :user_id, presence: true
  validates :event_id, presence: true
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :logged_in_user
  before_action :host_user, only: [:new, :create]
  before_action :guest_user, only: [:index, :edit, :update]
  before_action :host_or_guest_user, only: :destroy

  def index
    @user = User.find_by(id: params[:user_id])
    @invites = @user.invites
  end

  def new
    @users = User.all
    @event = Event.find_by(id: params[:event_id])
  end

  def create
    @event = Event.find_by(id: params[:event_id])
    invites = []
    params[:user_ids].each do |user_id, value|
      invites << (@event.invites.build(user_id: user_id)) if value == "1"
    end
    if invites.any? { |invite| invite.invalid? }
      render :new
    else
      invites.each { |invite| invite.save }
      i_l = invites.length 
      flash[:success] = "#{i_l} " + "invite".pluralize(i_l) + " sent!"
      redirect_to @event
    end
  end

  def edit
    @user = User.find_by(id: params[:user_id])
    @invite = Invite.find_by(id: params[:id])
    @event = @invite.event
  end

  def update
    @user = User.find_by(id: params[:user_id])
    @invite = Invite.find_by(id: params[:id])
    if @invite.update_attributes(update_invite_params)
      flash[:success] = "Reply updated!"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    # Invite found by host_or_guest_user before filter.
    @invite.destroy
    flash[:success] = "Invite canceled"
    redirect_to request.referrer || root_url
  end

  private

    def update_invite_params
      params.require(:invite).permit(:reply)
    end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_invite.html.erb
<li>
  <span class="event_link">
    <%= link_to invite.event.name, event_path(invite.event) %>
  </span>
  <span>
    Hosted by: 
    <%= link_to invite.event.host.name, user_path(invite.event.host) %>
  </span>
  <span>Current reply: <%= invite.reply %></span>
  <span class="change_links">
    <%= link_to "change reply", edit_user_invite_path(invite.user, invite) %>
    <%= link_to "delete", invite, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  </span>
</li>

app/views/invites/edit.html.erb
<% provide(:title, "Change reply") %>
<div class="row event_show">
  <div class="col-md-8 col-md-offset-2" >
    <h1><%= @event.name %></h1>
    <h2 class="host">
      Hosted by: 
      <%= link_to @event.host.name, @event.host %>
    </h2>
    <p class="description"><%= @event.description %></p>
    <span class="event_date">
      <%= formatted_date(@event.event_date, "Begins on ") %>
    </span>
    <span class="timestamp">
      Created <%= time_ago_in_words(@event.created_at) %> ago.
    </span>
    <span class="current_reply">Current reply: <%= @invite.reply %></span>
    <span class="reply_form">
      <%= form_for(:invite, url: user_invite_path(@user, @invite),
                            method: :patch) do |f| %>
        Change reply to: 

        <%= f.hidden_field :reply, value: @invite.reply %>

        <%= f.label :reply, class: "radio-inline" do %>
          <%= f.radio_button :reply, "yes", class: "radio-inline" %>
          <span>yes</span>
        <% end %>

        <%= f.label :reply, class: "radio-inline" do %>
          <%= f.radio_button :reply, "no", class: "radio-inline" %>
          <span>no</span>
        <% end %>

        <%= f.submit "Submit", class: "btn btn-primary reply_submit" %>
      <% end %>
    </span>
  </div>
</div>

app/views/invites/index.html.erb
<% provide(:title, "Invites") %>
<div class="row">
  <%= render "shared/user_sidebar" %>
  <div class="col-md-8">
    <h3>Invites (<%= @invites.count %>)</h3>
    <ul class="invites">
      <% if @invites.none? %>
        <li>Currently invited to no events.</li>
      <% end %>
      <%= render @invites %>
    </ul>
  </div>
</div>

app/views/invites/new.html.erb
<% provide(:title, "Invite users") %>
<h1>Invite Users</h1>

<%= form_tag new_event_invite_path(@event) do %>
  <ul class="users">
    <% @users.each do |user| %>
      <%= render partial: "shared/user_invite", locals: { user: user } %>
    <% end %>
  </ul>

  <%= submit_tag "Send invites", class: "btn btn-primary" %>
<% end %>