config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :invites, only: [:index, :edit, :update]
  end
  post '/events/:event_id/invites/new' => 'invites#create'
  resources :events, only: [:show, :new, :create, :destroy] do
    resources :invites, only: :new
  end
  resources :invites, only: :destroy

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_user_invite.html.erb
<li>
  <span><%= user.name %></span>
  <span class="timestamp">
    Member for <%= time_ago_in_words(user.created_at) %>
  </span>

  <%= label_tag :user_id, class: "invite_checkbox inline" do %>
    <%= hidden_field_tag "user_ids[#{user.id}]", "0" %>
    <%= check_box_tag "user_ids[#{user.id}]" %>
    <span>Invite this user</span>
  <% end %>
</li>

app/views/shared/_user_sidebar.html.erb
<aside class="col-md-4">
  <section class="user_info">
    <h1><%= @user.name %></h1>
    <span class="timestamp">
      Member for <%= time_ago_in_words(@user.created_at) %>
    </span>
    <% if current_user == @user %>
      <%= link_to "Create new event", new_event_path,
                                      class: "btn btn-primary" %>
    <% end %>
  </section>
</aside>